# general configuration
url: https://github.com/appcoocker
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/chef-hat.png"
  author: "AppCoocker"
  tagline: "Open source сообщество"
  include_content: true
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  #twitter: ""

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
